### ISSUE TITLE
Inner workings of a .cia file

### ISSUE THREAD

**Issue by miltoncandelero** [miltoncandelero/Boop#15]
**Intended functionality:**

As you load the .CIA file, in the selected files box it shows not the name of the cia file but the internal name of the app.

**But.. Why?**

Sometimes your .cia files have names like: 000400000F12EE00.cia and good luck remembering what that file was.

**The tip of the iceberg:**

Open any US cia with a hex editor, jump to 0x3B00 and THERE IT ISSSS... But now open a JP file.

Good luck decrypting that.

Maybe somebody knows a better way to find the name of an app inside the .cia?

**Comment by ksanislo** [comment]
The name data and icon are in the SMDH at the very end of the CIA file. This is documented on 3dbrew, but you can also find a python example of it here: https://github.com/ksanislo/TitleDB/blob/master/titledb/magic.py#L430

**Comment by ksanislo** [comment]
Oh, if you want to be able to display the icon as well... Here's a passable reference for how to translate the SMDH icon stored in the 3DS's native GPU format into a bitmap that you can use on PC.

https://github.com/ksanislo/TitleDB/blob/master/titledb/images.py

**Comment by miltoncandelero** [comment]
The SMDH is at the **END** of the CIA. That explains why I was struggling so much to understand everything.

I guess I missed that part. 
Thanks a lot!

**Comment by ksanislo** [comment]
You can just read in the last 14016 bytes and go for it, which will work with all 3DS native .cia... However, if you want to be able to support DSiWare CIA files, or just write code that isn't as terrible as mine, there are headers at the very beginning of the .cia file which you can use to find the offset of each of the data sections, including the real start of the SMDH at the end. I've been putting this part off in the TitleDB rewrite since I've had more pressing issues, but I intend to come back to it eventually and have it find the SMDH start and icon data properly when I have more time.

**Comment by miltoncandelero** [comment]
I enjoy writing terrible code.

Thanks a lot for your help. It works like a charm!

*You good sir are now a friend of the snek.*

**Comment by miltoncandelero** [comment]
@ksanislo Hey, if you want do an empty PR (or just add a space to the readme or whatever) so your name gets pulled from the github api in the about window.

***Don't ever forget, you are now a friend of the snek.***

**Comment by ksanislo** [comment]
Thanks, but I'm really not worried about getting credit for anything. After FBI blatantly cloned my QR scanner/installer without any acknowledgement, I decided that if I gave a shit about putting my name on things, the 3DS scene wasn't going to be the place for it. ;)
